kind: Service
apiVersion: v1
metadata:
  name: helloword-microsvc
  labels:
    app: helloworld-microsvc
spec:
  type: NodePort
  selector:
    app: helloword-microsvc
  ports:
    - port: 80
      targetPort: 3000
