kind: Service
apiVersion: v1
metadata:
  name: helloworld-microsvc
  labels:
    app: helloworld-microsvc
spec:
  type: LoadBalancer
  selector:
    app: helloworld-microsvc
  ports:
    - port: 80
      targetPort: 3000
