kind: Deployment
apiVersion: apps/v1
metadata:
  name: helloworld-microsvc
  labels:
    app: helloworld-microsvc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld-microsvc
  template:
    metadata:
      labels:
        app: helloworld-microsvc
    spec:
      containers:
        - name: helloworld-microsvc
          image: nsisodiya/helloworld-microsvc:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: TARGET
              value: World V1
